/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUI.java
 *
 * Created on Apr 18, 2012, 3:41:56 PM
 */
package GUI;

import javax.swing.JLabel;
import javax.swing.JLayeredPane;


/**
 *
 * @author atte
 */
public class GUI extends javax.swing.JFrame {

    /** Creates new form GUI */
    public GUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LABEL = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        slotti2 = new javax.swing.JLayeredPane();
        slotti213 = new javax.swing.JLabel();
        slotti212 = new javax.swing.JLabel();
        slotti211 = new javax.swing.JLabel();
        slotti210 = new javax.swing.JLabel();
        slotti29 = new javax.swing.JLabel();
        slotti28 = new javax.swing.JLabel();
        slotti27 = new javax.swing.JLabel();
        slotti26 = new javax.swing.JLabel();
        slotti25 = new javax.swing.JLabel();
        slotti24 = new javax.swing.JLabel();
        slotti23 = new javax.swing.JLabel();
        slotti22 = new javax.swing.JLabel();
        slotti21 = new javax.swing.JLabel();
        slotti20 = new javax.swing.JLabel();
        slotti1 = new javax.swing.JLayeredPane();
        slotti113 = new javax.swing.JLabel();
        slotti112 = new javax.swing.JLabel();
        slotti111 = new javax.swing.JLabel();
        slotti110 = new javax.swing.JLabel();
        slotti19 = new javax.swing.JLabel();
        slotti18 = new javax.swing.JLabel();
        slotti17 = new javax.swing.JLabel();
        slotti16 = new javax.swing.JLabel();
        slotti15 = new javax.swing.JLabel();
        slotti14 = new javax.swing.JLabel();
        slotti13 = new javax.swing.JLabel();
        slotti12 = new javax.swing.JLabel();
        slotti11 = new javax.swing.JLabel();
        slotti10 = new javax.swing.JLabel();
        slotti0 = new javax.swing.JLayeredPane();
        slotti013 = new javax.swing.JLabel();
        slotti012 = new javax.swing.JLabel();
        slotti011 = new javax.swing.JLabel();
        slotti010 = new javax.swing.JLabel();
        slotti09 = new javax.swing.JLabel();
        slotti08 = new javax.swing.JLabel();
        slotti07 = new javax.swing.JLabel();
        slotti06 = new javax.swing.JLabel();
        slotti05 = new javax.swing.JLabel();
        slotti04 = new javax.swing.JLabel();
        slotti03 = new javax.swing.JLabel();
        slotti02 = new javax.swing.JLabel();
        slotti01 = new javax.swing.JLabel();
        slotti00 = new javax.swing.JLabel();
        jakopakka = new javax.swing.JLayeredPane();
        jakopakka00 = new javax.swing.JLabel();
        jakopakka2 = new javax.swing.JLabel();
        jakopakka1 = new javax.swing.JLabel();
        jakopakka0 = new javax.swing.JLabel();
        maalipakat = new javax.swing.JLayeredPane();
        maalipakka0 = new javax.swing.JLabel();
        maalipakka1 = new javax.swing.JLabel();
        maalipakka2 = new javax.swing.JLabel();
        maalipakka3 = new javax.swing.JLabel();
        takaSlotti0 = new javax.swing.JLayeredPane();
        takaSlotti11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LABEL.setFont(new java.awt.Font("Dialog", 1, 18));
        LABEL.setText("Tekstiä");

        slotti2.setPreferredSize(new java.awt.Dimension(71, 370));

        slotti213.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti213.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti213.setName("pelipakka 2 13"); // NOI18N
        slotti213.setBounds(0, 260, 71, 96);
        slotti2.add(slotti213, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti212.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti212.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti212.setName("pelipakka 2 12"); // NOI18N
        slotti212.setBounds(0, 240, 71, 96);
        slotti2.add(slotti212, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti211.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti211.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti211.setName("pelipakka 2 11"); // NOI18N
        slotti211.setBounds(0, 220, 71, 96);
        slotti2.add(slotti211, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti210.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti210.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti210.setName("pelipakka 2 10"); // NOI18N
        slotti210.setBounds(0, 200, 71, 96);
        slotti2.add(slotti210, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti29.setName("pelipakka 2 9"); // NOI18N
        slotti29.setBounds(0, 180, 71, 96);
        slotti2.add(slotti29, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti28.setName("pelipakka 2 8"); // NOI18N
        slotti28.setBounds(0, 160, 71, 96);
        slotti2.add(slotti28, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti27.setName("pelipakka 2 7"); // NOI18N
        slotti27.setBounds(0, 140, 71, 96);
        slotti2.add(slotti27, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti26.setName("pelipakka 2 6"); // NOI18N
        slotti26.setBounds(0, 120, 71, 96);
        slotti2.add(slotti26, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti25.setName("pelipakka 2 5"); // NOI18N
        slotti25.setBounds(0, 100, 71, 96);
        slotti2.add(slotti25, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti24.setName("pelipakka 2 4"); // NOI18N
        slotti24.setBounds(0, 80, 71, 96);
        slotti2.add(slotti24, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti23.setName("pelipakka 2 3"); // NOI18N
        slotti23.setBounds(0, 60, 71, 96);
        slotti2.add(slotti23, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti22.setName("pelipakka 2 2"); // NOI18N
        slotti22.setBounds(0, 40, 71, 96);
        slotti2.add(slotti22, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti21.setName("pelipakka 2 1"); // NOI18N
        slotti21.setBounds(0, 20, 71, 96);
        slotti2.add(slotti21, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti20.setName("pelipakka 2 0"); // NOI18N
        slotti20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slotti20MouseClicked(evt);
            }
        });
        slotti20.setBounds(0, 0, 71, 96);
        slotti2.add(slotti20, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti2.setBounds(210, 140, 71, 380);
        jLayeredPane1.add(slotti2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti1.setPreferredSize(new java.awt.Dimension(71, 370));

        slotti113.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti113.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti113.setName("pelipakka 1 13"); // NOI18N
        slotti113.setBounds(0, 260, 71, 96);
        slotti1.add(slotti113, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti112.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti112.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti112.setName("pelipakka 1 12"); // NOI18N
        slotti112.setBounds(0, 240, 71, 96);
        slotti1.add(slotti112, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti111.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti111.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti111.setName("pelipakka 1 11"); // NOI18N
        slotti111.setBounds(0, 220, 71, 96);
        slotti1.add(slotti111, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti110.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti110.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti110.setName("pelipakka 1 10"); // NOI18N
        slotti110.setBounds(0, 200, 71, 96);
        slotti1.add(slotti110, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti19.setName("pelipakka 1 9"); // NOI18N
        slotti19.setBounds(0, 180, 71, 96);
        slotti1.add(slotti19, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti18.setName("pelipakka 1 8"); // NOI18N
        slotti18.setBounds(0, 160, 71, 96);
        slotti1.add(slotti18, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti17.setName("pelipakka 1 7"); // NOI18N
        slotti17.setBounds(0, 140, 71, 96);
        slotti1.add(slotti17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti16.setName("pelipakka 1 6"); // NOI18N
        slotti16.setBounds(0, 120, 71, 96);
        slotti1.add(slotti16, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti15.setName("pelipakka 1 5"); // NOI18N
        slotti15.setBounds(0, 100, 71, 96);
        slotti1.add(slotti15, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti14.setName("pelipakka 1 4"); // NOI18N
        slotti14.setBounds(0, 80, 71, 96);
        slotti1.add(slotti14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti13.setName("pelipakka 1 3"); // NOI18N
        slotti13.setBounds(0, 60, 71, 96);
        slotti1.add(slotti13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti12.setName("pelipakka 1 2"); // NOI18N
        slotti12.setBounds(0, 40, 71, 96);
        slotti1.add(slotti12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti11.setName("pelipakka 1 1"); // NOI18N
        slotti11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slotti11MouseClicked(evt);
            }
        });
        slotti11.setBounds(0, 20, 71, 96);
        slotti1.add(slotti11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti10.setName("pelipakka 1 0"); // NOI18N
        slotti10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slotti10MouseClicked(evt);
            }
        });
        slotti10.setBounds(0, 0, 71, 96);
        slotti1.add(slotti10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti1.setBounds(100, 140, 71, 380);
        jLayeredPane1.add(slotti1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti0.setPreferredSize(new java.awt.Dimension(71, 370));

        slotti013.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti013.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti013.setName("pelipakka 0 13"); // NOI18N
        slotti013.setBounds(0, 260, 71, 96);
        slotti0.add(slotti013, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti012.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti012.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti012.setName("pelipakka 0 12"); // NOI18N
        slotti012.setBounds(0, 240, 71, 96);
        slotti0.add(slotti012, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti011.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti011.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti011.setName("pelipakka 0 11"); // NOI18N
        slotti011.setBounds(0, 220, 71, 96);
        slotti0.add(slotti011, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti010.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti010.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti010.setName("pelipakka 0 10"); // NOI18N
        slotti010.setBounds(0, 200, 71, 96);
        slotti0.add(slotti010, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti09.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti09.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti09.setName("pelipakka 0 9"); // NOI18N
        slotti09.setBounds(0, 180, 71, 96);
        slotti0.add(slotti09, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti08.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti08.setName("pelipakka 0 8"); // NOI18N
        slotti08.setBounds(0, 160, 71, 96);
        slotti0.add(slotti08, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti07.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti07.setName("pelipakka 0 7"); // NOI18N
        slotti07.setBounds(0, 140, 71, 96);
        slotti0.add(slotti07, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti06.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti06.setName("pelipakka 0 6"); // NOI18N
        slotti06.setBounds(0, 120, 71, 96);
        slotti0.add(slotti06, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti05.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti05.setName("pelipakka 0 5"); // NOI18N
        slotti05.setBounds(0, 100, 71, 96);
        slotti0.add(slotti05, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti04.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti04.setName("pelipakka 0 4"); // NOI18N
        slotti04.setBounds(0, 80, 71, 96);
        slotti0.add(slotti04, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti03.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti03.setName("pelipakka 0 3"); // NOI18N
        slotti03.setBounds(0, 60, 71, 96);
        slotti0.add(slotti03, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti02.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti02.setName("pelipakka 0 2"); // NOI18N
        slotti02.setBounds(0, 40, 71, 96);
        slotti0.add(slotti02, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti01.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti01.setName("pelipakka 0 1"); // NOI18N
        slotti01.setBounds(0, 20, 71, 96);
        slotti0.add(slotti01, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        slotti00.setLabelFor(slotti0);
        slotti00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slotti00.setName("pelipakka 0 0"); // NOI18N
        slotti00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slotti00MouseClicked(evt);
            }
        });
        slotti00.setBounds(0, 0, 71, 96);
        slotti0.add(slotti00, javax.swing.JLayeredPane.DEFAULT_LAYER);

        slotti0.setBounds(0, 140, 71, 380);
        jLayeredPane1.add(slotti0, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jakopakka.setPreferredSize(new java.awt.Dimension(205, 96));

        jakopakka00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        jakopakka00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jakopakka00.setBounds(0, 0, 71, 96);
        jakopakka.add(jakopakka00, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jakopakka2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        jakopakka2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jakopakka2.setName("jakopakka 0 2"); // NOI18N
        jakopakka2.setBounds(130, 0, 71, 96);
        jakopakka.add(jakopakka2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jakopakka1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        jakopakka1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jakopakka1.setName("jakopakka 0 1"); // NOI18N
        jakopakka1.setBounds(110, 0, 71, 96);
        jakopakka.add(jakopakka1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jakopakka0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        jakopakka0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jakopakka0.setName("jakopakka 0 0"); // NOI18N
        jakopakka0.setBounds(90, 0, 71, 96);
        jakopakka.add(jakopakka0, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jakopakka.setBounds(0, 0, 205, 96);
        jLayeredPane1.add(jakopakka, javax.swing.JLayeredPane.DEFAULT_LAYER);

        maalipakat.setPreferredSize(new java.awt.Dimension(350, 96));

        maalipakka0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        maalipakka0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        maalipakka0.setName("maalipakka 0 0"); // NOI18N
        maalipakka0.setBounds(0, 0, 71, 96);
        maalipakat.add(maalipakka0, javax.swing.JLayeredPane.DEFAULT_LAYER);

        maalipakka1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        maalipakka1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        maalipakka1.setName("maalipakka 1 0"); // NOI18N
        maalipakka1.setBounds(90, 0, 71, 96);
        maalipakat.add(maalipakka1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        maalipakka2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        maalipakka2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        maalipakka2.setName("maalipakka 2 0"); // NOI18N
        maalipakka2.setBounds(180, 0, 71, 96);
        maalipakat.add(maalipakka2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        maalipakka3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/B.png"))); // NOI18N
        maalipakka3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        maalipakka3.setName("maalipakka 0 3"); // NOI18N
        maalipakka3.setBounds(270, 0, 71, 96);
        maalipakat.add(maalipakka3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        maalipakat.setBounds(280, 0, 350, 96);
        jLayeredPane1.add(maalipakat, javax.swing.JLayeredPane.DEFAULT_LAYER);

        takaSlotti11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/EMPTYSLOT.png"))); // NOI18N
        takaSlotti11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        takaSlotti11.setName("jakopakka 0 0"); // NOI18N
        takaSlotti11.setBounds(0, 0, 71, 96);
        takaSlotti0.add(takaSlotti11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        takaSlotti0.setBounds(0, 140, 70, 100);
        jLayeredPane1.add(takaSlotti0, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(269, 269, 269)
                    .addComponent(LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(91, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(201, 201, 201)
                    .addComponent(LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(286, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slotti00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slotti00MouseClicked
        klikattuSiirraPelipakasta(slotti00);
    }//GEN-LAST:event_slotti00MouseClicked

    private void slotti10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slotti10MouseClicked
        klikattuSiirraPelipakasta(slotti10);
    }//GEN-LAST:event_slotti10MouseClicked

    private void slotti20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slotti20MouseClicked
        klikattuSiirraPelipakasta(slotti20);
    }//GEN-LAST:event_slotti20MouseClicked

    private void slotti11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slotti11MouseClicked
        klikattuSiirraPelipakasta(slotti11);
    }//GEN-LAST:event_slotti11MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new GUI().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LABEL;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jakopakka;
    private javax.swing.JLabel jakopakka0;
    private javax.swing.JLabel jakopakka00;
    private javax.swing.JLabel jakopakka1;
    private javax.swing.JLabel jakopakka2;
    private javax.swing.JLayeredPane maalipakat;
    private javax.swing.JLabel maalipakka0;
    private javax.swing.JLabel maalipakka1;
    private javax.swing.JLabel maalipakka2;
    private javax.swing.JLabel maalipakka3;
    private javax.swing.JLayeredPane slotti0;
    private javax.swing.JLabel slotti00;
    private javax.swing.JLabel slotti01;
    private javax.swing.JLabel slotti010;
    private javax.swing.JLabel slotti011;
    private javax.swing.JLabel slotti012;
    private javax.swing.JLabel slotti013;
    private javax.swing.JLabel slotti02;
    private javax.swing.JLabel slotti03;
    private javax.swing.JLabel slotti04;
    private javax.swing.JLabel slotti05;
    private javax.swing.JLabel slotti06;
    private javax.swing.JLabel slotti07;
    private javax.swing.JLabel slotti08;
    private javax.swing.JLabel slotti09;
    private javax.swing.JLayeredPane slotti1;
    private javax.swing.JLabel slotti10;
    private javax.swing.JLabel slotti11;
    private javax.swing.JLabel slotti110;
    private javax.swing.JLabel slotti111;
    private javax.swing.JLabel slotti112;
    private javax.swing.JLabel slotti113;
    private javax.swing.JLabel slotti12;
    private javax.swing.JLabel slotti13;
    private javax.swing.JLabel slotti14;
    private javax.swing.JLabel slotti15;
    private javax.swing.JLabel slotti16;
    private javax.swing.JLabel slotti17;
    private javax.swing.JLabel slotti18;
    private javax.swing.JLabel slotti19;
    private javax.swing.JLayeredPane slotti2;
    private javax.swing.JLabel slotti20;
    private javax.swing.JLabel slotti21;
    private javax.swing.JLabel slotti210;
    private javax.swing.JLabel slotti211;
    private javax.swing.JLabel slotti212;
    private javax.swing.JLabel slotti213;
    private javax.swing.JLabel slotti22;
    private javax.swing.JLabel slotti23;
    private javax.swing.JLabel slotti24;
    private javax.swing.JLabel slotti25;
    private javax.swing.JLabel slotti26;
    private javax.swing.JLabel slotti27;
    private javax.swing.JLabel slotti28;
    private javax.swing.JLabel slotti29;
    private javax.swing.JLayeredPane takaSlotti0;
    private javax.swing.JLabel takaSlotti11;
    // End of variables declaration//GEN-END:variables
    private GUISovellus guiSovellus;
    private KomentoKirjasto komentoKirjasto;
    private JLabel aktiivinen;
    private int aktiivistenMaaraJosUseampi;
    
    private void klikattuSiirra(JLabel korttiLabel){
       if(guiSovellus.onkoKortti(korttiLabel.getName())){
            if(aktiivinen == null){    
                if(guiSovellus.onkoPelipakanPaallimmainen(korttiLabel.getName())){
                    aktiivinen = korttiLabel;
                    korttiLabel.setEnabled(false);
                }
            }
            else {
                //if(aktiivistenMaaraJosUseampi != 0) TÄTÄ JOUTUU EHKÄ KÄYTTÄMÄÄN
                guiSovellus.pushKomento(komentoKirjasto.siirra(aktiivinen.getName(), korttiLabel.getName()));
                paivita();
            }
        }
    }
    private void klikattuSiirraPelipakasta(JLabel korttiLabel){
        if(guiSovellus.onkoKortti(korttiLabel.getName())){
            if(aktiivinen == null){
                if(guiSovellus.onkoPelipakanPaallimmainen(korttiLabel.getName())){
                    aktiivinen = korttiLabel;
                    korttiLabel.setEnabled(false);
                }
                else{
                    aktiivistenMaaraJosUseampi = guiSovellus.montaPelipakassaPaalla(korttiLabel.getName()) +1;
                    aktiivinen = korttiLabel;
                    maalaaAlaspain((JLayeredPane) korttiLabel.getParent(), aktiivistenMaaraJosUseampi);
                }
            }
            else {
                if(aktiivistenMaaraJosUseampi == 0)
                    guiSovellus.pushKomento(komentoKirjasto.siirra(aktiivinen.getName(), korttiLabel.getName()));
                else
                    guiSovellus.pushKomento(komentoKirjasto.siirraMonta(aktiivinen.getName(), korttiLabel.getName(), aktiivistenMaaraJosUseampi));
                paivita();
                
            }
        }
    }
    private void tyhjennaAktiivinen(){
        if(aktiivistenMaaraJosUseampi == 0){
            aktiivinen.setEnabled(true);
            aktiivinen = null;
        }
        else{
            poistaMaalausAlaspain((JLayeredPane) aktiivinen.getParent(), aktiivistenMaaraJosUseampi);
            aktiivinen = null;
            aktiivistenMaaraJosUseampi = 0;
        }
    }
    
    private void maalaaAlaspain(JLayeredPane pane, int i){
        for(int j = pane.getComponentCount() -1; j >= i; j--){
            JLabel korttiLabel = (javax.swing.JLabel) pane.getComponent(j);
            if(korttiLabel.isVisible())
                korttiLabel.setEnabled(false);
        }
    }
    private void poistaMaalausAlaspain(JLayeredPane pane, int i){
        for(int j = pane.getComponentCount() -1; j >= i; j--){
            JLabel korttiLabel = (javax.swing.JLabel) pane.getComponent(j);
            korttiLabel.setEnabled(true);
        }
    }
    
    private void paivitaTila(JLabel korttiLabel){
        if(guiSovellus.onkoKortti(korttiLabel.getName())){
            korttiLabel.setIcon(guiSovellus.getKortinKuva(korttiLabel.getName()));
            korttiLabel.setVisible(true);
        }
        else
            korttiLabel.setVisible(false);
    }
    
    private void paivitaTilaBorderilla(JLabel korttiLabel){
        if(guiSovellus.onkoKortti(korttiLabel.getName()))
            korttiLabel.setIcon(guiSovellus.getKortinKuva(korttiLabel.getName()));
        else
            korttiLabel.setIcon(guiSovellus.getTyhjaKortti());
        }
    
    public void alusta(GUISovellus sovellus){
        guiSovellus = sovellus;
        aktiivinen = null;
        aktiivistenMaaraJosUseampi = 0;
        komentoKirjasto = new KomentoKirjasto();
        paivita();
        this.setVisible(true);
    }
    public void paivita(){

        if(aktiivinen != null)
            tyhjennaAktiivinen();

        if(guiSovellus.onkoJakopakassaVaarinpainKortteja())
            jakopakka00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/BACK_0.png")));
        else
            jakopakka00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/EMPTYSLOT.png")));
        
        
        for(int i = jakopakka.getComponentCount() -1; i > 0; i--){
            javax.swing.JLabel korttiLabel = (javax.swing.JLabel) jakopakka.getComponent(i);
            paivitaTila(korttiLabel);
        }
        for(int i = maalipakat.getComponentCount() -1; i >= 0; i--){
            javax.swing.JLabel korttiLabel = (javax.swing.JLabel) maalipakat.getComponent(i);
            paivitaTilaBorderilla(korttiLabel);
        }
        for(int i = slotti0.getComponentCount() -1; i >= 0; i--){
            javax.swing.JLabel korttiLabel = (javax.swing.JLabel) slotti0.getComponent(i);
            paivitaTila(korttiLabel);
        }
        for(int i = slotti1.getComponentCount() -1; i >= 0; i--){
            javax.swing.JLabel korttiLabel = (javax.swing.JLabel) slotti1.getComponent(i);
            
            paivitaTila(korttiLabel);
        }
        for(int i = slotti2.getComponentCount() -1; i >= 0; i--){
            javax.swing.JLabel korttiLabel = (javax.swing.JLabel) slotti2.getComponent(i);
            
            paivitaTila(korttiLabel);
        }
    }
}
